In [15]:
import pandas as pd  
import numpy as np  
import matplotlib.pyplot as plt  
import seaborn as seabornInstance 
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression
from sklearn import metrics
from scipy.io import arff
%matplotlib inline

In [48]:
dataset = pd.read_csv('/home/karu/Documents/COMP309/Kaggle-Competition/completion/Pre-Processed Datasets/Challange-WB-T1_scikit.csv')

In [49]:
dataset.shape

(787, 4)

In [50]:
dataset.describe()
dataset.head()

            X          Y       difficulty    Time
0  178.308430 -38.231307             Easy   120.0
1  172.622902 -40.752098             Easy   180.0
2  174.093759 -39.272137  Advanced-Expert  2160.0
3  175.138814 -39.727109         Advanced   420.0
4  169.146338 -45.077094             Easy    90.0

In [63]:
X = dataset['X'].values.reshape(-1,1)
y = dataset['Time'].values.reshape(-1,1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
regressor = LinearRegression()  
regressor.fit(X_train, y_train) #training the algorithm

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [64]:
#To retrieve the intercept:
print(regressor.intercept_)
#For retrieving the slope:
print(regressor.coef_)

[4991.10004232]
[[-26.80258661]]

In [65]:
y_pred = regressor.predict(X_test)

In [62]:
df = pd.DataFrame({'Actual': y_test.flatten(), 'Predicted': y_pred.flatten()})
df

     Actual   Predicted
0     420.0  267.834341
1      15.0  479.090739
2    1440.0  333.723856
3     310.0  367.912844
4      60.0  301.790184
5      90.0  246.577309
6      15.0  200.723613
7      15.0  276.715477
8     960.0  418.024639
9     180.0  190.354177
10      7.5  316.474442
11     50.0  230.798411
12     20.0  413.711865
13      5.0  201.285843
14    120.0  208.421660
15    120.0  306.847782
16     60.0  488.679360
17    420.0  457.237168
18      5.0  286.469216
19    300.0  424.704293
20     20.0  519.983926
21    120.0  500.740030
22     75.0  484.832876
23     60.0  263.231335
24    330.0  360.569746
25     60.0  439.149067
26    180.0  180.538975
27     90.0  492.589664
28    960.0  379.693774
29    180.0  330.949766
..      ...         ...
128    20.0  333.140082
129   420.0  375.473152
130   420.0  276.859919
131   300.0  466.171183
132    28.0  275.432577
133    90.0  221.192705
134   120.0  459.204972
135   540.0  335.285319
136   180.0  269.866610
137   150.0  203.748522
138   420.0  457.186702
139    30.0  497.594411
140   210.0  219.847248
141  1200.0  416.126462
142    60.0  461.533925
143    60.0  320.876760
144    30.0  357.001123
145  1440.0  415.603842
146  1920.0  472.322242
147    60.0  298.073835
148    45.0  302.199330
149   105.0  416.701792
150    10.0  201.734460
151    30.0  434.883224
152   960.0  462.435703
153    60.0  458.228883
154   120.0  284.188934
155   160.0  417.363636
156   720.0  278.781577
157    75.0  272.379784

[158 rows x 2 columns]